title: FLibGoLite - Just enough for free OPDS 
author:
  name: Serguei Vine
  email: vinser@outlook.com
description: "Multiplatform lightweight OPDS server with SQLite database book search index"

remote_theme: jekyll/minima
markdown: GFM

header_pages:
  - README.md
  - README_RU.md
  - README_UK.md
  - README.docker.md