url: https://github.com/vinser/flibgolite
title: FLibGoLite - Just enough for free OPDS 
description: "Multiplatform lightweight OPDS server with SQLite database book search index"
# author:
#   name: Serguei Vine
#   email: vinser@outlook.com

theme: minima
# markdown: GFM

header_pages:
  - index.md
  - guide_ru.md
  - guide_uk.md
  - docker.md
