url: https://github.io/vinser/flibgolite
title: FLibGoLite - Just enough for free OPDS 
description: "Multiplatform lightweight OPDS server with SQLite database book search index"
author:
  name: Serguei Vine
  email: vinser@outlook.com

remote_theme: jekyll/minima
markdown: GFM
minima:
  skin: auto

header_pages:
  - index.md
  - guide_ru.md
  - guide_uk.md
  - docker.md
