library:
  # Selfexplained folders
  STOCK: "/var/flibgolite/books/stock"
  NEW: "/var/flibgolite/books/new"
  TRASH: "/var/flibgolite/books/trash"

genres:
  TREE_FILE: "/var/flibgolite/config/genres.xml"
  # Alternative genres tree can be used (Russian only, sorry)
  # TREE_FILE: "config/alt_genres.xml"

database:
  DSN: "/var/flibgolite/dbdata/flibgolite.db"
  # Delay before start each new acquisitions processing
  POLL_DELAY: 30
  # Maximum simultaneous new aquisitios processing threads
  MAX_SCAN_THREADS: 1

logs:
  # Logs are here
  OPDS: "/dev/stdout"
  SCAN: "/dev/stdout"
  LEVEL: "W"

opds:
  # OPDS-server port so opds can be found at http://<server name or IP-address or localhost>:8085/opds
  PORT: 8085
  # OPDS-server title that is displayed in a book reader
  TITLE: "FLib Go Go Go!!!"
  # OPDS feeds entries page size
  PAGE_SIZE: 30

locales:
  # Locales folder. You can add your own locale file there like en.yml, ru.yml, uk.yml
  DIR: "/var/flibgolite/config/locales"
  # Default english locale for opds feeds (bookreaders opds menu tree) can be changed to:
  # "uk" for Ukrainian,
  # "ru" for Russian
  DEFAULT: "en"
  # Accept only these languages publications. Add others if needed please.
  ACCEPTED: "en, ru, uk"
